interface meter {
    use instrument.{instrument-kind};
    // new: func(provider: instrument-provider) -> meter; // TODO: be sure to implement in sdk
    u64-counter: func(name: string) -> instrument-kind;
    f64-counter: func(name: string) -> instrument-kind;
    u64-observable-counter: func(name: string) -> instrument-kind;
    f64-observable-counter: func(name: string) -> instrument-kind;
    i64-up-down-counter: func(name: string) -> instrument-kind;
    f64-up-down-counter: func(name: string) -> instrument-kind;
    i64-observable-up-down-counter: func(name: string) -> instrument-kind;
    f64-observable-up-down-counter: func(name: string) -> instrument-kind;
    u64-gauge: func(name: string) -> instrument-kind;
    f64-gauge: func(name: string) -> instrument-kind;
    i64-gauge: func(name: string) -> instrument-kind;
    u64-observable-gauge: func(name: string) -> instrument-kind;
    i64-observable-gauge: func(name: string) -> instrument-kind;
    f64-observable-gauge: func(name: string) -> instrument-kind;
    f64-histogram: func(name: string) -> instrument-kind;
    u64-histogram: func(name: string) -> instrument-kind;
}