// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package wasi_io_poll

import (
	"runtime"
	"unsafe"

	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wit_runtime"
)

//go:wasmimport wasi:io/poll@0.2.0 [resource-drop]pollable
func resourceDropPollable(handle int32)

type Pollable struct {
	handle *wit_runtime.Handle
}

func (self *Pollable) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Pollable) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Pollable) Handle() int32 {
	return self.handle.Use()
}

func (self *Pollable) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropPollable(handle)
	}
}

func PollableFromOwnHandle(handleValue int32) *Pollable {
	handle := wit_runtime.MakeHandle(handleValue)
	value := &Pollable{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropPollable(handleValue)
		}
	}, 0)
	return value
}

func PollableFromBorrowHandle(handleValue int32) *Pollable {
	return PollableFromOwnHandle(handleValue)
}

//go:wasmimport wasi:io/poll@0.2.0 [method]pollable.ready
func wasm_import_method_pollable_ready(arg0 int32) int32

func (self *Pollable) Ready() bool {

	result := wasm_import_method_pollable_ready((self).Handle())
	return (result != 0)

}

//go:wasmimport wasi:io/poll@0.2.0 [method]pollable.block
func wasm_import_method_pollable_block(arg0 int32)

func (self *Pollable) Block() {

	wasm_import_method_pollable_block((self).Handle())

}

//go:wasmimport wasi:io/poll@0.2.0 poll
func wasm_import_poll(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Poll(in []*Pollable) []uint32 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (2 * 4), 4))
	slice := in
	length := uint32(len(slice))
	result := wit_runtime.Allocate(pinner, uintptr(length*4), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*4)
		*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = (element).Handle()

	}

	wasm_import_poll(uintptr(result), length, returnArea)
	value := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result0 := value
	return result0

}
