// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package add represents the exported interface "docs:adder/add@0.1.0".
package add

import (
	"go.bytecodealliance.org/cm"
)

// Numbers represents the record "docs:adder/add@0.1.0#numbers".
//
//	record numbers {
//		x: u32,
//		y: u32,
//	}
type Numbers struct {
	_ cm.HostLayout `json:"-"`
	X uint32        `json:"x"`
	Y uint32        `json:"y"`
}
