// Code generated by wit-bindgen-go. DO NOT EDIT.

package add

// Exports represents the caller-defined exports from "docs:adder/add@0.1.0".
var Exports struct {
	// Add represents the caller-defined, exported function "add".
	//
	//	add: func(nums: numbers) -> u32
	Add func(nums Numbers) (result uint32)
}
