// Code generated by wit-bindgen-go. DO NOT EDIT.

package tracing

// This file contains wasmimport and wasmexport declarations for "wasi:otel@0.2.0-draft".

//go:wasmimport wasi:otel/tracing@0.2.0-draft on-start
//go:noescape
func wasmimport_OnStart(context0 *uint8, context1 uint32, context2 *uint8, context3 uint32, context4 uint32, context5 uint32, context6 *[2]string, context7 uint32)

//go:wasmimport wasi:otel/tracing@0.2.0-draft on-end
//go:noescape
func wasmimport_OnEnd(span *SpanData)

//go:wasmimport wasi:otel/tracing@0.2.0-draft outer-span-context
//go:noescape
func wasmimport_OuterSpanContext(result *SpanContext)
