// Code generated by wit-bindgen-go. DO NOT EDIT.

package tracing

import (
	"go.bytecodealliance.org/cm"
)

func lower_SpanContext(v SpanContext) (f0 *uint8, f1 uint32, f2 *uint8, f3 uint32, f4 uint32, f5 uint32, f6 *[2]string, f7 uint32) {
	f0, f1 = cm.LowerString(v.TraceID)
	f2, f3 = cm.LowerString(v.SpanID)
	f4 = (uint32)(v.TraceFlags)
	f5 = (uint32)(cm.BoolToU32(v.IsRemote))
	f6, f7 = cm.LowerList(v.TraceState)
	return
}
