// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package main

import (
	"runtime"

	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wit_runtime"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

// Unused, but present to make the compiler happy
func main() {}
