// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package wasi_otel_logs

import (
	"runtime"
	"unsafe"

	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wasi_clocks_wall_clock"
	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wasi_otel_tracing"
	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wasi_otel_types"
	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wit_runtime"
	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wit_types"
)

type InstrumentationScope = wasi_otel_types.InstrumentationScope
type Resource = wasi_otel_types.Resource
type Value = string
type KeyValue = wasi_otel_types.KeyValue
type SpanId = string
type TraceId = string
type TraceFlags = wasi_otel_tracing.TraceFlags
type Datetime = wasi_clocks_wall_clock.Datetime

// Represents the recording of an event.
type LogRecord struct {
	// Time when the event occurred.
	Timestamp wit_types.Option[wasi_clocks_wall_clock.Datetime]
	// Time when the event was observed.
	ObservedTimestamp wit_types.Option[wasi_clocks_wall_clock.Datetime]
	// The severity text(also known as log level).
	SeverityText wit_types.Option[string]
	// The numerical value of the severity ranging from 1-24.
	SeverityNumber wit_types.Option[uint8]
	// The body of the log record.
	Body wit_types.Option[string]
	// Additional information about the specific event occurrence.
	Attributes wit_types.Option[[]wasi_otel_types.KeyValue]
	// Name that identifies the class / type of event.
	EventName wit_types.Option[string]
	// Describes the source of the log.
	Resource wit_types.Option[wasi_otel_types.Resource]
	// Describes the scope that emitted the log.
	InstrumentationScope wit_types.Option[wasi_otel_types.InstrumentationScope]
	// Request trace id.
	TraceId wit_types.Option[string]
	// Request span id.
	SpanId wit_types.Option[string]
	// W3C trace flag.
	TraceFlags wit_types.Option[wasi_otel_tracing.TraceFlags]
}

//go:wasmimport wasi:otel/logs@0.2.0-draft on-emit
func wasm_import_on_emit(arg0 uintptr)

func OnEmit(data LogRecord) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (56 + 36*4), 8))

	switch (data).Timestamp.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), 0)) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).Timestamp.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), 0)) = int8(int32(1))
		*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)) = int64((payload).Seconds)
		*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 16)) = int32((payload).Nanoseconds)

	default:
		panic("unreachable")
	}

	switch (data).ObservedTimestamp.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), 24)) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).ObservedTimestamp.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), 24)) = int8(int32(1))
		*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32)) = int64((payload).Seconds)
		*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 40)) = int32((payload).Nanoseconds)

	default:
		panic("unreachable")
	}

	switch (data).SeverityText.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), 48)) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).SeverityText.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), 48)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 2*4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 1*4))) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}

	switch (data).SeverityNumber.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 3*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).SeverityNumber.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 3*4))) = int8(int32(1))
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (49 + 3*4))) = int8(int32(payload))

	default:
		panic("unreachable")
	}

	switch (data).Body.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 4*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).Body.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 4*4))) = int8(int32(1))
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 6*4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 5*4))) = uint32(uintptr(uintptr(utf80)))

	default:
		panic("unreachable")
	}

	switch (data).Attributes.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 7*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).Attributes.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 7*4))) = int8(int32(1))
		slice := payload
		length := uint32(len(slice))
		result := wit_runtime.Allocate(pinner, uintptr(length*(4*4)), 4)
		for index, element := range slice {
			base := unsafe.Add(result, index*(4*4))
			utf81 := unsafe.Pointer(unsafe.StringData((element).Key))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Key)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf81)))
			utf82 := unsafe.Pointer(unsafe.StringData((element).Value))
			pinner.Pin(utf82)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Value)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf82)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 9*4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 8*4))) = uint32(uintptr(uintptr(result)))

	default:
		panic("unreachable")
	}

	switch (data).EventName.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 10*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).EventName.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 10*4))) = int8(int32(1))
		utf83 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf83)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 12*4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 11*4))) = uint32(uintptr(uintptr(utf83)))

	default:
		panic("unreachable")
	}

	switch (data).Resource.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 13*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).Resource.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 13*4))) = int8(int32(1))
		slice6 := (payload).Attributes
		length8 := uint32(len(slice6))
		result7 := wit_runtime.Allocate(pinner, uintptr(length8*(4*4)), 4)
		for index, element := range slice6 {
			base := unsafe.Add(result7, index*(4*4))
			utf84 := unsafe.Pointer(unsafe.StringData((element).Key))
			pinner.Pin(utf84)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Key)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf84)))
			utf85 := unsafe.Pointer(unsafe.StringData((element).Value))
			pinner.Pin(utf85)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Value)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf85)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 15*4))) = uint32(length8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 14*4))) = uint32(uintptr(uintptr(result7)))

		switch (payload).SchemaUrl.Tag() {
		case wit_types.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 16*4))) = int8(int32(0))

		case wit_types.OptionSome:
			payload := (payload).SchemaUrl.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 16*4))) = int8(int32(1))
			utf89 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf89)
			*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 18*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 17*4))) = uint32(uintptr(uintptr(utf89)))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}

	switch (data).InstrumentationScope.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 19*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).InstrumentationScope.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 19*4))) = int8(int32(1))
		utf810 := unsafe.Pointer(unsafe.StringData((payload).Name))
		pinner.Pin(utf810)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 21*4))) = uint32(uint32(len((payload).Name)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 20*4))) = uint32(uintptr(uintptr(utf810)))

		switch (payload).Version.Tag() {
		case wit_types.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 22*4))) = int8(int32(0))

		case wit_types.OptionSome:
			payload := (payload).Version.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 22*4))) = int8(int32(1))
			utf811 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf811)
			*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 24*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 23*4))) = uint32(uintptr(uintptr(utf811)))

		default:
			panic("unreachable")
		}

		switch (payload).SchemaUrl.Tag() {
		case wit_types.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 25*4))) = int8(int32(0))

		case wit_types.OptionSome:
			payload := (payload).SchemaUrl.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 25*4))) = int8(int32(1))
			utf812 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf812)
			*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 27*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 26*4))) = uint32(uintptr(uintptr(utf812)))

		default:
			panic("unreachable")
		}
		slice15 := (payload).Attributes
		length17 := uint32(len(slice15))
		result16 := wit_runtime.Allocate(pinner, uintptr(length17*(4*4)), 4)
		for index, element := range slice15 {
			base := unsafe.Add(result16, index*(4*4))
			utf813 := unsafe.Pointer(unsafe.StringData((element).Key))
			pinner.Pin(utf813)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Key)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf813)))
			utf814 := unsafe.Pointer(unsafe.StringData((element).Value))
			pinner.Pin(utf814)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Value)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf814)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 29*4))) = uint32(length17)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 28*4))) = uint32(uintptr(uintptr(result16)))

	default:
		panic("unreachable")
	}

	switch (data).TraceId.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 30*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).TraceId.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 30*4))) = int8(int32(1))
		utf818 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf818)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 32*4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 31*4))) = uint32(uintptr(uintptr(utf818)))

	default:
		panic("unreachable")
	}

	switch (data).SpanId.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 33*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).SpanId.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 33*4))) = int8(int32(1))
		utf819 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf819)
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 35*4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 34*4))) = uint32(uintptr(uintptr(utf819)))

	default:
		panic("unreachable")
	}

	switch (data).TraceFlags.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 36*4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (data).TraceFlags.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 36*4))) = int8(int32(1))
		*(*int8)(unsafe.Add(unsafe.Pointer(returnArea), (49 + 36*4))) = int8(int32(payload))

	default:
		panic("unreachable")
	}
	wasm_import_on_emit(returnArea)

}
