# Updates the files in the `dist` and `types/interfaces` directories.
# Run this if the Spin app isn't reflecting the latest version of the WIT files and/or SDK
build-sdk:
	npm install
	npx jco guest-types -o ./types ./wit
	npm run build
