FROM rust:1.91.0-slim-bookworm AS stable-binary-provider

RUN rustup target add wasm32-wasip1 wasm32-wasip2

RUN apt update \
    && apt install -y --no-install-recommends \
        git \
        g++ \
        libssl-dev \
        pkg-config

# Clone a version of Spin with WASI OTel
RUN git clone --branch wasi-otel-logs https://github.com/asteurer/spin \
    && cd spin \
    && git checkout 622a628d11aba5c4234302a2e59f60c45280a2f6

# Build Spin
RUN cd spin \
    && cargo build --release

FROM rust:1.91.0-slim-bookworm
COPY --from=stable-binary-provider /spin/target/release/spin /usr/local/bin

# Add compilation targets for building Spin apps
RUN rustup target add wasm32-wasip1 wasm32-wasip2

# Add integration test suite build dependencies
RUN apt update \
    && apt install -y --no-install-recommends \
        libssl-dev \
        pkg-config
