FROM rust:1.91.0-slim-bookworm AS stable-binary-provider

RUN rustup target add wasm32-wasip1 wasm32-wasip2

RUN apt update \
    && apt install -y --no-install-recommends \
        git \
        g++ \
        libssl-dev \
        pkg-config

# Install a version of Spin with WASI OTel
RUN cargo install \
    --git https://github.com/asteurer/spin \
    --rev cc558b2ec0cb2cd0619c6a410325bd165f632f1e \
    spin-cli

FROM rust:1.91.0-slim-bookworm
COPY --from=stable-binary-provider /usr/local/cargo/bin/spin /usr/local/cargo/bin/spin

# Add dependencies for building Spin apps
RUN rustup target add wasm32-wasip1 wasm32-wasip2
RUN cargo install --git https://github.com/asteurer/componentize-go

# Add integration test suite build dependencies
RUN apt update \
    && apt install -y --no-install-recommends \
        libssl-dev \
        pkg-config
