// This is modeled after the `LogRecordProcessor`
// See https://opentelemetry.io/docs/specs/otel/logs/sdk/#logrecordprocessor

// interface logging {
//     on-emit: func();
//     enabled: func(); // TODO: according to the specs, this is still in development. Should we include?
//     shutdown: func();
//     force-flush: func();
// }