// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:otel@0.2.0-draft

package wit_exports

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}
