// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:otel@0.2.0-rc.2

package wit_exports

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}
