// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:otel@0.2.0-draft

package wasi_otel_types

import (
	"github.com/bytecodealliance/wit-bindgen/wit_types"
)

// The key part of attribute `key-value` pairs.
type Key = string

// The value part of attribute `key-value` pairs.
//
// This corresponds with the `AnyValue` type defined in the [attribute spec](https://opentelemetry.io/docs/specs/otel/common/#anyvalue).
// Because WIT doesn't support recursive types, the data needs to be serialized. JSON is used as the encoding format.
type Value = string

// A key-value pair describing an attribute.
type KeyValue struct {
	// The attribute name.
	Key string
	// The attribute value.
	Value string
}

// An immutable representation of the entity producing telemetry as attributes.
type Resource struct {
	// Attributes that identify the resource.
	Attributes []KeyValue
	// The schema URL to be recorded in the emitted resource.
	SchemaUrl wit_types.Option[string]
}

// Describes the instrumentation scope that produced telemetry.
type InstrumentationScope struct {
	// Name of the instrumentation scope.
	Name string
	// The library version.
	Version wit_types.Option[string]
	// Schema URL used by this library.
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	SchemaUrl wit_types.Option[string]
	// Specifies the instrumentation scope attributes to associate with emitted telemetry.
	Attributes []KeyValue
}
