// Code generated by wit-bindgen-go. DO NOT EDIT.

package add

// This file contains wasmimport and wasmexport declarations for "docs:adder@0.1.0".

//go:wasmexport docs:adder/add@0.1.0#add
//export docs:adder/add@0.1.0#add
func wasmexport_Add(nums0 uint32, nums1 uint32) (result0 uint32) {
	nums := lift_Numbers((uint32)(nums0), (uint32)(nums1))
	result := Exports.Add(nums)
	result0 = (uint32)(result)
	return
}
