// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package wasi_clocks_monotonic_clock

import (
	"github.com/calebschoepp/opentelemetry-wasi/wit_component/wasi_io_poll"
)

type Pollable = wasi_io_poll.Pollable

// An instant in time, in nanoseconds. An instant is relative to an
// unspecified initial value, and can only be compared to instances from
// the same monotonic-clock.
type Instant = uint64

// A duration of time, in nanoseconds.
type Duration = uint64

//go:wasmimport wasi:clocks/monotonic-clock@0.2.0 now
func wasm_import_now() int64

func Now() uint64 {

	result := wasm_import_now()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.2.0 resolution
func wasm_import_resolution() int64

func Resolution() uint64 {

	result := wasm_import_resolution()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.2.0 subscribe-instant
func wasm_import_subscribe_instant(arg0 int64) int32

func SubscribeInstant(when uint64) *wasi_io_poll.Pollable {

	result := wasm_import_subscribe_instant(int64(when))
	return wasi_io_poll.PollableFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport wasi:clocks/monotonic-clock@0.2.0 subscribe-duration
func wasm_import_subscribe_duration(arg0 int64) int32

func SubscribeDuration(when uint64) *wasi_io_poll.Pollable {

	result := wasm_import_subscribe_duration(int64(when))
	return wasi_io_poll.PollableFromOwnHandle(int32(uintptr(result)))

}
