// This is only here to satisfy the build tools.
package example:test@0.1.0;

world http-trigger {
    export wasi:http/incoming-handler@0.2.0;
    include wasi:otel/imports@0.2.0-draft;
    import fermyon:spin/key-value@2.0.0;
}
