name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup target add wasm32-wasip1 wasm32-wasip2

      - name: Install cargo-vet
        run: cargo install cargo-vet

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Run vetters
        run: just vet

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup target add wasm32-wasip1 wasm32-wasip2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25.8.2

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Setup golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Linters
        run: just lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup target add wasm32-wasip1 wasm32-wasip2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Check Formatting
        run: just format

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint, format, vet] # Ensure code is linted and formatted before running tests
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup target add wasm32-wasip1 wasm32-wasip2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Setup Wasmtime (for Go unit tests)
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "40.0.1"

      - name: Setup componentize-go
        uses: bytecodealliance/componentize-go/.github/actions/setup-componentize-go@main
        with:
          version: 'v0.2.0'

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "v3.6.1"

      - name: Run Tests
        run: just test
